### ISSUE TITLE
Build fails in Ubuntu 18.04.1

### ISSUE THREAD

**Issue by jayemel** [teejee2008/ukuu#90]
I am attempting to build using the supplied instructions. I have installed the required dependencies but the compile errors out with:

Gtk/TerminalWindow.vala:241.19-241.40: error: Argument 1: Cannot convert from `string' to `unowned char[]?'
		term.feed_child("%s\n".printf(command), -1);
		                ^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 42 warning(s)
makefile:21: recipe for target 'app-gtk' failed
make[1]: *** [app-gtk] Error 1
make[1]: Leaving directory '/home/jlevine/ukuu/src'
makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

 -- Josh

**Comment by peci1** [comment]
The fix for this bug completely broke build on 14.04. 

```
$make all
Package vte-2.91 was not found in the pkg-config search path.
Perhaps you should add the directory containing `vte-2.91.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vte-2.91' found
/bin/bash: line 0: test: -lt: unary operator expected
make[1]: Entering directory `/home/peci1/apps/ukuu/src'
# app
valac -X -D'GETTEXT_PACKAGE="ukuu"' --Xcc="-lm" --thread \
		Common/*.vala Console/*.vala Utility/*.vala \
		-o ukuu \
		--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gee-0.8 --pkg libsoup-2.4 --pkg json-glib-1.0

....

Compilation succeeded - 14 warning(s)
# app-gtk
valac -X -D'GETTEXT_PACKAGE="ukuu"' --Xcc="-lm" -D VTE_291 --thread \
		Common/*.vala Gtk/*.vala Utility/*.vala Utility/Gtk/*.vala \
		-o ukuu-gtk \
		--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gtk+-3.0 --pkg gee-0.8 --pkg json-glib-1.0 --pkg -D VTE_291
error: Package `-D' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
make[1]: *** [app-gtk] Error 1
make[1]: Leaving directory `/home/peci1/apps/ukuu/src'
make: *** [all] Error 2
```
And also, 14.04 only has vte 2.90. When I tried to manually change the hardcoded 2.91 version to 2.90 in the pkg-config search, the error changes to this:

```
# app-gtk
valac -X -D'GETTEXT_PACKAGE="ukuu"' --Xcc="-lm" -D VTE_291_OLD --thread \
		Common/*.vala Gtk/*.vala Utility/*.vala Utility/Gtk/*.vala \
		-o ukuu-gtk \
		--pkg glib-2.0 --pkg gio-unix-2.0 --pkg posix --pkg gtk+-3.0 --pkg gee-0.8 --pkg json-glib-1.0 --pkg -D VTE_291_OLD
error: Package `-D' not found in specified Vala API directories or GObject-Introspection GIR directories
```

**Comment by teejee2008** [comment]
vte 2.90 and Ubuntu 14.04 is very old. Please use a newer Linux distribution.

**Comment by gothicVI** [comment]
@peci1 14.04 is not getting security updates anymore from April next year. You might want to upgrade.

**Comment by peci1** [comment]
You're both right. But Trusty is not yet EOL, and upgrading the system is not so easy because we have several robots running Trusty we need to use continuously, and we haven't scheduled any upgrade time yet (it probably gets more priority as April approaches). 

The thing is, if I revert this commit, ukuu still builds without a problem. So would it be possible to introduce some if-else branch for vte 2.90? If not, I'll just stay with the last working commit on my Trusty systems and will hope the kernel guys won't break something else until Trusty is EOL.
